# Generated by Django 5.0.6 on 2026-03-07 05:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0006_resumesuggestion_discarded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillResourceLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('skill_name', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=512)),
                ('resource_type', models.CharField(choices=[('course', 'Course'), ('tutorial', 'Tutorial'), ('documentation', 'Documentation'), ('project', 'Project')], max_length=20)),
                ('url', models.URLField(max_length=1024)),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_hours', models.FloatField(default=0.0)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearningRoadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('target_role', models.CharField(max_length=255)),
                ('gap_snapshot', models.JSONField(help_text='Snapshot of missing skills used to generate this roadmap')),
                ('overall_progress', models.IntegerField(default=0, help_text='Progress 0-100')),
                ('estimated_total_hours', models.IntegerField(default=0)),
                ('estimated_completion_days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('skill_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('phase', models.IntegerField(help_text='1, 2, or 3')),
                ('order', models.IntegerField()),
                ('estimated_hours', models.IntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('module_progress', models.IntegerField(default=0, help_text='Progress 0-100')),
                ('completed', models.BooleanField(default=False)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='roadmaps.learningroadmap')),
            ],
            options={
                'ordering': ['phase', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=512)),
                ('resource_type', models.CharField(choices=[('course', 'Course'), ('tutorial', 'Tutorial'), ('documentation', 'Documentation'), ('project', 'Project')], max_length=20)),
                ('url', models.URLField(max_length=1024)),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_minutes', models.IntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('priority', models.IntegerField(default=2, help_text='1=Primary, 2=Secondary, 3=Optional')),
                ('completed', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='roadmaps.roadmapmodule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='learningroadmap',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'resume'), name='unique_active_roadmap_per_resume'),
        ),
    ]
