# Generated by Django 5.0.6 on 2026-02-22 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(db_index=True, max_length=255)),
                ('overall_gap_score', models.IntegerField(default=0)),
                ('normalized', models.BooleanField(default=True)),
                ('confirmed_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
