# Generated by Django 5.0.6 on 2026-02-27 18:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleSkillMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role_name', models.CharField(db_index=True, max_length=255)),
                ('skill_name', models.CharField(db_index=True, max_length=255)),
                ('priority_score', models.IntegerField(default=50)),
                ('market_demand', models.IntegerField(default=50)),
            ],
            options={
                'indexes': [models.Index(fields=['role_name', 'skill_name'], name='skills_role_role_na_98539d_idx')],
                'unique_together': {('role_name', 'skill_name')},
            },
        ),
    ]
