# Generated by Django 5.0.6 on 2026-02-22 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('refund', 'Refund')], db_index=True, max_length=10)),
                ('source', models.CharField(choices=[('resume', 'Resume Analysis'), ('interview', 'Interview Simulation'), ('roadmap', 'Roadmap Generation'), ('manual', 'Manual Adjustment')], db_index=True, max_length=20)),
                ('amount', models.IntegerField()),
                ('reference_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
