# Generated by Django 5.0.6 on 2026-02-22 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('model_used', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('cost_estimate', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
