# Generated by Django 5.0.6 on 2026-02-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='strengths',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='weaknesses',
            field=models.JSONField(default=list),
        ),
    ]
