# Generated by Django 5.0.6 on 2026-02-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_strengths_resume_weaknesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='raw_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
