# Generated by Django 5.0.6 on 2026-02-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_raw_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='target_role',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
