# Generated by Django 5.0.6 on 2026-02-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_resume_target_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumesuggestion',
            name='discarded',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
