# Generated by Django 5.0.6 on 2026-02-22 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('job_type', models.CharField(choices=[('resume', 'Resume Analysis'), ('roadmap', 'Roadmap Generation'), ('interview', 'Interview Evaluation')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('result_reference', models.UUIDField(blank=True, db_index=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
